# Generated by Django 2.1 on 2020-02-09 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sender_file', models.FileField(blank=True, upload_to='work/employer/')),
                ('reciever_file', models.FileField(blank=True, upload_to='work/employee/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('reciever', models.ForeignKey(limit_choices_to={'office_tag': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='task_reciever', to='accounts.Profile')),
                ('sender', models.ForeignKey(limit_choices_to={'office_tag': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='task_sender', to='accounts.Profile')),
            ],
        ),
    ]
